apiVersion: v1
kind: Service
metadata:
  labels:
    service: loc-producer
  name: loc-producer
spec:
  ports:
  - name: "5555"
    port: 5555
    targetPort: 5555
    nodePort: 30003
  selector:
    service: loc-producer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: loc-producer
  name: loc-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: loc-producer
  template:
    metadata:
      labels:
        service: loc-producer
    spec:
      containers:
      - image: chipato/loc_prod_api:latest
        name: loc-producer